### PR TITLE
fix(api): use correct field lengths for file processors

### LINKED ISSUE #458: Processors have incorrect truncation lengths
### What Went Wrong?

`CBXProcessor` and other processors have arbitrary truncation lengths.

### How Can We Reproduce This?

1. Try to extract metadata with an incorrect value (eg, ASIN has a UUID)
2. See failure for length of 20 being written to max length 10 field ASIN in database

### What Should Have Happened?

Truncation should match with expected field lengths.

### Screenshots or Error Messages (Optional)

https://github.com/grimmory-tools/grimmory/blob/7dd1d503a24cb9908434244ec1d083cfe426d574/booklore-api/src/main/java/org/booklore/service/fileprocessor/CbxProcessor.java#L138-L172

### Any Ideas on How to Fix This? (Optional)

This should apply to all processors.

### Your Setup

Grimmory 2.3.0

### Before Submitting

- [x] I've searched existing issues and confirmed this bug hasn't been reported yet

### PR DESCRIPTION
**Pull request by imnotjames**
## Description

The various processors truncate extracted metadata fields so they properly fit in database metadata fields.

However, the ASIN, ISBN, and language fields were improperly truncated, and were too long which caused database errors.

This updates the truncation length to 10 for language, 10 for ASIN, 10 for ISBN10, and 13 for ISBN13.

**Linked Issue:** Fixes #458

## Changes

* Updates truncation lengths for file processors to match BookMetadataEntity field lengths

## Summary by CodeRabbit

* **Refactor**
  * Standardized metadata field length constraints for ISBN numbers, language codes, and Amazon Standard Identifiers across all supported ebook formats (AZW3, EPUB, MOBI, FB2, CBX, PDF).
  * Enhanced book description field capacity for AZW3 format processing.

### CODE REVIEW

File: booklore-api/src/main/java/org/booklore/service/fileprocessor/Azw3Processor.java [hunk 1]
```diff
@@ -106,20 +106,20 @@ private void setBookMetadata(BookEntity bookEntity) {
 
         metadata.setTitle(truncate(azw3Metadata.getTitle(), 1000));
         metadata.setSubtitle(truncate(azw3Metadata.getSubtitle(), 1000));
-        metadata.setDescription(truncate(azw3Metadata.getDescription(), 2000));
+        metadata.setDescription(truncate(azw3Metadata.getDescription(), 5000));
```
Comment (imnotjames) [inline booklore-api/src/main/java/org/booklore/service/fileprocessor/Azw3Processor.java:109]: Matching with other processors

**Review by balazs-szucs — APPROVED** [review]
Thank you!
