### PR TITLE
fix(dto): add DailyListeningDto and update session-related DTOs to use LocalDate

### LINKED ISSUE #401: CBX to EPUB conversion fails
### What Went Wrong?

on nightly, when i try to download a cbx on my kobo, it fails, and nothing is downloaded. this is not an issue on stable

### How Can We Reproduce This?

1. in grimmory, enable "Convert CBX to EPUB"
2. add a cbx book to the kobo shelf
3. on the kobo device, perform a sync, and attempt to download said book

### What Should Have Happened?

the book should be converted and downloaded to the kobo device

### Screenshots or Error Messages (Optional)

```
2026-04-07T00:34:03.021+10:00  INFO 1 --- [booklore-api] [at-handler-1470] o.b.service.kobo.KoboEntitlementService  : Synced 1 tags to Kobo
2026-04-07T00:34:03.951+10:00  INFO 1 --- [booklore-api] [at-handler-1477] o.b.service.kobo.CbxConversionService    : Starting CBX to EPUB conversion for: [redacted].cbz
2026-04-07T00:34:04.511+10:00 ERROR 1 --- [booklore-api] [at-handler-1477] o.b.service.book.BookDownloadService     : Failed to download kobo book 920: Cannot lazily initialize collection of role 'org.booklore.model.entity.BookMetadataEntity.authors' with key '920' (no session)

org.hibernate.LazyInitializationException: Cannot lazily initialize collection of role 'org.booklore.model.entity.BookMetadataEntity.authors' with key '920' (no session)
        at org.hibernate.collection.spi.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:647) ~[hibernate-core-7.3.0.Final.jar!/:7.3.0.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:232) ~[hibernate-core-7.3.0.Final.jar!/:7.3.0.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:159) ~[hibernate-core-7.3.0.Final.jar!/:7.3.0.Final]
        at org.hibernate.collection.spi.PersistentList.isEmpty(PersistentList.java:154) ~[hibernate-core-7.3.0.Final.jar!/:7.3.0.Final]
        at org.booklore.service.kobo.CbxConversionService.createBookMetadataModel(CbxConversionService.java:506) ~[!/:0.0.1-SNAPSHOT]
        at org.booklore.service.kobo.CbxConversionService.addContentOpf(CbxConversionService.java:405) ~[!/:0.0.1-SNAPSHOT]
        at org.booklore.service.kobo.CbxConversionService.executeCbxConversion(CbxConversionService.java:141) ~[!/:0.0.1-SNAPSHOT]
        at org.booklore.service.kobo.CbxConversionService.convertCbxToEpub(CbxConversionService.java:111) ~[!/:0.0.1-SNAPSHOT]
        at org.booklore.service.book.BookDownloadService.downloadKoboBook(BookDownloadService.java:269) ~[!/:0.0.1-SNAPSHOT]
        at org.booklore.controller.KoboController.downloadBook(KoboController.java:163) ~[!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:252) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:184) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:934) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:853) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:86) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:866) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1000) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:892) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:874) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:710) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:128) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-11.0.20.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:315) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.booklore.config.security.filter.KoreaderAuthFilter.doFilterInternal(KoreaderAuthFilter.java:33) ~[!/:0.0.1-SNAPSHOT]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.booklore.config.security.filter.JwtAuthenticationFilter.doFilterInternal(JwtAuthenticationFilter.java:48) ~[!/:0.0.1-SNAPSHOT]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.booklore.config.security.filter.ImageCachingFilter.doFilterInternal(ImageCachingFilter.java:25) ~[!/:0.0.1-SNAPSHOT]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.booklore.config.security.filter.SharedArrayBufferHeaderFilter.doFilterInternal(SharedArrayBufferHeaderFilter.java:27) ~[!/:0.0.1-SNAPSHOT]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:235) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:493) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:354) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:86) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:132) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:101) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:132) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:86) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:181) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.booklore.config.security.filter.KoboAuthFilter.doFilterInternal(KoboAuthFilter.java:83) ~[!/:0.0.1-SNAPSHOT]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:96) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:231) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:244) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:337) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:228) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:141) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:237) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:195) ~[spring-security-web-7.0.4.jar!/:7.0.4]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.filter.ServletRequestPathFilter.doFilter(ServletRequestPathFilter.java:52) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebSecurityConfiguration.java:317) ~[spring-security-config-7.0.4.jar!/:7.0.4]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:355) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:272) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:110) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:199) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:165) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:77) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:113) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:83) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:72) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:397) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:903) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1779) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at java.base/java.lang.VirtualThread.run(Unknown Source) ~[na:na]

### Any Ideas on How to Fix This? (Optional)

_No response_

### Your Setup

- Grimmory Version: nightly-20260406-d693364
- OS: Ubuntu Server 24.04.4 LTS
- Installation: Docker

### Before Submitting

- [x] I've searched existing issues and confirmed this bug hasn't been reported yet

### LINKED ISSUE #427: Bookdrop finalizer fails with "Book ID missing after import"
### What Went Wrong?

After reviewing and finalizing a bookdrop import, i get lots of failed imports (nearly 100%). The error shown in the frontend is "Processing failed: File not found: Book ID missing after import". 

The logs show the following: 
```
2026-04-08T18:43:58.277+02:00  INFO 1 --- [booklore-api] [at-handler-1983] o.b.service.bookdrop.BookDropService     : Moved file id=500, name=Schattenspiel - Charlotte Link.epub from '/bookdrop/Charlotte Link/Schattenspiel (33)/Schattenspiel - Charlotte Link.epub' to '/books/Charlotte Link/Schattenspiel/Schattenspiel - Charlotte Link (1993).epub'
2026-04-08T18:43:58.876+02:00  INFO 1 --- [booklore-api] [at-handler-1983] o.b.s.m.sidecar.SidecarMetadataWriter    : Wrote cover file to: /books/Charlotte Link/Schattenspiel/Schattenspiel - Charlotte Link (1993).cover.jpg 
2026-04-08T18:43:58.887+02:00  INFO 1 --- [booklore-api] [at-handler-1983] o.b.s.m.sidecar.SidecarMetadataWriter    : Wrote sidecar metadata to: /books/Charlotte Link/Schattenspiel/Schattenspiel - Charlotte Link (1993).metadata.json      
2026-04-08T18:43:58.924+02:00  INFO 1 --- [booklore-api] [at-handler-1983] o.b.service.bookdrop.BookDropService     : Cleaned up target file '/books/Charlotte Link/Schattenspiel/Schattenspiel - Charlotte Link (1993).epub' after processing exception for file id=500
2026-04-08T18:43:58.925+02:00  WARN 1 --- [booklore-api] [at-handler-1983] o.b.service.bookdrop.BookDropService     : Finalization failed (non-exception) for file id=500, name=Schattenspiel - Charlotte Link.epub, message=Processing failed: File not found: Book ID missing after import
```

The book file is still present in the bookdrop folder. It is not moved to the target library folder. The book itself, however, is imported into Grimmory's library. Trying to read it simply results in a blank browser tab. 

### How Can We Reproduce This?

1. Drop some books into the bookdrop folder. The dropped books may or may not be organized in Calibre style. 
2. Start bookdrop scan
3. Mark the desired books to import and finalize the bookdrop import. 
4. Wait for the error message to appear. 

### What Should Have Happened?

The book should not only be shown as imported, but also import the actual ebook file. 

### Screenshots or Error Messages (Optional)

_No response_

### Any Ideas on How to Fix This? (Optional)

This did not happen on the latest available build of booklore. However since i did not trust it, i wiped the whole library for migrating to grimmory today, and only encountered this problems after then. So maybe it got introduced with some bookdrop factoring, i guess. 

### Your Setup

- Grimmory Version: nightly-20260407
- OS: Debian Stable with Docker
- Browser: Vivaldi
- Storage: Local SSD, folders mounted via bind mount to the container (no docker volume but a filesystem path)

### Before Submitting

- [x] I've searched existing issues and confirmed this bug hasn't been reported yet

### LINKED ISSUE #492: Deletion of author results in unhandled exception
### What Went Wrong?

When i want to delete an author, the WebUI simply states that the deletion has failed. The container logs show an unhandled exception.

### How Can We Reproduce This?

1. Try to delete an author
2. Check stack trace. 

### What Should Have Happened?

The author should have been deleted. 

### Screenshots or Error Messages (Optional)

```
2026-04-13T12:56:10.962+02:00 ERROR 1 --- [booklore-api] [cat-handler-208] o.b.exception.GlobalExceptionHandler     : Unhandled exception: Cannot lazily initialize collection of role 'org.booklore.model.ent
ity.AuthorEntity.bookMetadataEntityList' with key '57' (no session)

org.hibernate.LazyInitializationException: Cannot lazily initialize collection of role 'org.booklore.model.entity.AuthorEntity.bookMetadataEntityList' with key '57' (no session)
        at org.hibernate.collection.spi.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:647) ~[hibernate-core-7.3.0.Final.jar!/:7.3.0.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:232) ~[hibernate-core-7.3.0.Final.jar!/:7.3.0.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:620) ~[hibernate-core-7.3.0.Final.jar!/:7.3.0.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:142) ~[hibernate-core-7.3.0.Final.jar!/:7.3.0.Final]
        at org.hibernate.collection.spi.PersistentSet.iterator(PersistentSet.java:164) ~[hibernate-core-7.3.0.Final.jar!/:7.3.0.Final]
        at org.booklore.service.AuthorMetadataService.deleteAuthors(AuthorMetadataService.java:195) ~[!/:0.0.1-SNAPSHOT]
        at org.booklore.controller.AuthorController.deleteAuthors(AuthorController.java:170) ~[!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:359) ~[spring-aop-7.0.6.jar!/:7.0.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-7.0.6.jar!/:7.0.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:158) ~[spring-aop-7.0.6.jar!/:7.0.6]
        at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.proceed(AuthorizationManagerBeforeMethodInterceptor.java:271) ~[spring-security-core-7.0.4.jar!/:7.0.
4]
        at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.attemptAuthorization(AuthorizationManagerBeforeMethodInterceptor.java:266) ~[spring-security-core-7.0
.4.jar!/:7.0.4]
        at org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor.invoke(AuthorizationManagerBeforeMethodInterceptor.java:197) ~[spring-security-core-7.0.4.jar!/:7.0.4
]
        at org.springframework.security.config.annotation.method.configuration.DeferringMethodInterceptor.invoke(DeferringMethodInterceptor.java:44) ~[spring-security-config-7.0.4.jar!/:7.0.4]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-7.0.6.jar!/:7.0.6]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:719) ~[spring-aop-7.0.6.jar!/:7.0.6]
        at org.booklore.controller.AuthorController$$SpringCGLIB$$0.deleteAuthors(<generated>) ~[!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:252) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:184) ~[spring-web-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:934) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:853) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:86) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:866) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1000) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:925) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:651) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:874) ~[spring-webmvc-7.0.6.jar!/:7.0.6]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:710) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:128) ~[tomcat-embed-core-11.0.20.jar!/:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-11.0.20.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:107) ~[tomcat-embed-core-11.0.20.jar!/:na]
```

### Any Ideas on How to Fix This? (Optional)

At first i thought of a problem with my OIDC provider because of the 'no session', but this is unrelated. 
No matter which author i try to delete, even multiple ones, it is always referring to the AuthorEntity with the key '57'. 

### Your Setup

- Grimmory nightly from 2026-04-13
- Debian Stable
- Docker
- Browser: Vivaldi

### Before Submitting

- [x] I've searched existing issues and confirmed this bug hasn't been reported yet

### PR DESCRIPTION
**Pull request by balazs-szucs**
## Description

**Linked Issue:** Fixes #401

## Changes

This pull request introduces several improvements and refactorings to the backend data access and service layers, focusing on notebook entry management, reading session analytics, and repository query optimizations. The changes include the addition of a new unified JPA view for notebook entries, migration of several complex native queries to JPQL using this view, and enhancements to repository methods for better paging and maintainability. Additionally, the reading session service logic is refactored for improved time zone handling and period calculations.

**Notebook Entries Refactor and Repository Improvements:**

* Introduced a new JPA entity `NotebookEntryView` that unifies highlights, notes, and bookmarks into a single immutable view, simplifying queries and data access for notebook entries.
* Refactored `NotebookEntryRepository` to use `NotebookEntryView` and migrated all major native SQL queries to JPQL, improving maintainability and leveraging JPA features. This includes changes to the main entry, book list, and book-with-count queries.

**Repository Query and Paging Enhancements:**

* Updated several repository methods to use `Pageable` for paging instead of manual `LIMIT`/`OFFSET` in native queries, and refactored methods to use JPQL instead of native SQL. This affects both `BookRepository` and `BookOpdsRepository`, improving consistency and Spring Data compatibility. 

**Reading Session Analytics Refactor:**

* Refactored `ReadingSessionService` to improve time zone handling (now using offset in seconds) and introduced helper methods for calculating period bounds (year/month) for analytics queries. This makes the code more robust and easier to extend

**DTO and Projection Updates:**

* Updated DTOs for reading sessions and notebook analytics to use `LocalDate` instead of day-of-week integers, providing more precise and flexible date handling. 

## Summary by CodeRabbit

* **Performance Improvements**
  * Added a DB index, optimized queries for reading/listening stats, improved eager loading for library paths, and removed a redundant connection-test query.

* **New Features**
  * Unified read-only notebook entries view (highlights/notes/bookmarks) and added daily listening DTO.

* **Backend Improvements**
  * Simplified metadata update API, switched analytics to period/range queries with timezone-second handling, and moved batch jobs to cursor-based pagination.

* **Tests**
  * Updated and added tests to match repository/service changes.

### CODE REVIEW

File: booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java [hunk 1]
```diff
@@ -52,9 +52,30 @@ public class ReadingSessionService {
     private final UserRepository userRepository;
     private final UserBookProgressRepository userBookProgressRepository;
 
-    private String getTimezoneOffset() {
-        ZoneOffset offset = ZoneId.systemDefault().getRules().getOffset(Instant.now());
-        return offset.getId().equals("Z") ? "+00:00" : offset.getId();
+    private int getTimezoneOffsetSeconds() {
```
Comment (zachyale) [inline booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java]: We cannot be computing a single "current" offset based on the current time and reusing it for all historical/future analytics. This causes a drift when accounting for daylight savings time, which could lead to a complete shift in the period's day/month/year depending on when the session is. We need to replace this with zone consistent handling for the target period.

Kind of insane that's how it used to be, but we need to be better here

File: booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java [hunk 2]
```diff
@@ -52,9 +52,30 @@ public class ReadingSessionService {
...
+        return ZoneId.systemDefault().getRules().getOffset(Instant.now()).getTotalSeconds();
+    }
+
+    record PeriodBounds(Instant start, Instant end) {}
+
+    private PeriodBounds computeYearBounds(int year) {
```
Comment (zachyale) [inline booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java:56]: `computeYearBounds`/`computeMonthBounds` _are_ zone aware, but downstream groupings are still fixed offset. This mismatch can drop sessions like I mentioned above in day/month/year barriers in DST timezones. We should align all aspects to one approach, using zone consistent handling

File: booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java [hunk 3]
```diff
@@ -166,16 +193,30 @@ public List<FavoriteReadingDaysResponse> getFavoriteReadingDays(Integer year, In
...
-                .map(dto -> FavoriteReadingDaysResponse.builder()
-                        .dayOfWeek(dto.getDayOfWeek())
-                        .dayName(dayNames[dto.getDayOfWeek() - 1])
-                        .sessionCount(dto.getSessionCount())
-                        .totalDurationSeconds(dto.getTotalDurationSeconds())
-                        .build())
+        var dailyResults = readingSessionRepository.findFavoriteReadingDaysByUser(userId, bounds.start(), bounds.end(), getTimezoneOffsetSeconds());
+
+        // Aggregate per-date results by ISO day-of-week (Mon=1, Sun=7) in Java for dialect portability
+        Map<DayOfWeek, long[]> weekdayTotals = new EnumMap<>(DayOfWeek.class);
```
Comment (zachyale) [inline booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java:211]: The previous approach used a 0-index on Sunday, this switches to Monday first, existing uses of this haven't been updated to assume Monday first which means the dates will be wrong

File: booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java [hunk 4]
```diff
@@ -488,12 +529,15 @@ public List<SessionScatterResponse> getSessionScatter(int year) {
...
+        PeriodBounds bounds = computeYearBounds(year);
+
+        return readingSessionRepository.findSessionScatterByUserAndYear(userId, bounds.start(), bounds.end(), getTimezoneOffsetSeconds(),
+                        PageRequest.of(0, 500))
                 .stream()
                 .map(dto -> SessionScatterResponse.builder()
                         .hourOfDay(dto.getHourOfDay())
                         .durationMinutes(dto.getDurationMinutes())
-                        .dayOfWeek(dto.getDayOfWeek())
+                        .dayOfWeek(dto.getSessionDate().getDayOfWeek().getValue())
```
Comment (zachyale) [inline booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java]: Session scatter switches to Monday first day of week, but current chart datasets still use Sunday first, no?

File: booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java [hunk 5]
```diff
@@ -771,12 +835,13 @@ public List<ListeningAuthorResponse> getListeningAuthorStats() {
...
         Long userId = authenticationService.getAuthenticatedUser().getId();
-        return readingSessionRepository.findListeningSessionScatterByUser(userId, getTimezoneOffset())
+        return readingSessionRepository.findListeningSessionScatterByUser(userId, getTimezoneOffsetSeconds(),
+                        PageRequest.of(0, 500))
                 .stream()
                 .map(dto -> SessionScatterResponse.builder()
                         .hourOfDay(dto.getHourOfDay())
                         .durationMinutes(dto.getDurationMinutes())
-                        .dayOfWeek(dto.getDayOfWeek())
+                        .dayOfWeek(dto.getSessionDate().getDayOfWeek().getValue())
```
Comment (zachyale) [inline booklore-api/src/main/java/org/booklore/service/ReadingSessionService.java]: Similar issue as mentioned re: Sunday/Monday

**Review by zachyale — CHANGES_REQUESTED** [review]
Some notes re: issues on Sunday/Monday indexing, and an existing (but still wrong) implementation of timezone awareness that is DST agnostic.

Depending on how you proceed you may need to address the favourite days chart/session archetype charts w/ these indexing related changes.

**Comment by balazs-szucs** [comment]
> Some notes re: issues on Sunday/Monday indexing, and an existing (but still wrong) implementation of timezone awareness that is DST agnostic.
> 
> Depending on how you proceed you may need to address the favourite days chart/session archetype charts w/ these indexing related changes.

Thanks for the review. This stuff was interesting, bit painful, but i think i got it:

For context:  [670644a](https://github.com/grimmory-tools/grimmory/pull/403/commits/670644acedb837a750ea5b9d348157a852f3a69e)

- Every query now returns raw UTC Instant values (or SessionTimestampDto with UTC startTime), and the service converts each session individually with instant.atZone(zone)
- computeYearBounds produces UTC instants based on ZoneId.systemDefault(), and the Java-side grouping uses the same ZoneId. A session near a DST transition that falls inside the bounds will always be bucketed into the correct local date/hour.
- toSundayFirstDow does (dow.getValue() % 7) + 1, so that should i think the good conversion for the mismatch


the obvious trade-off/ still problematic parts are the following:
- findAllSessionStartTimesByUser has no period filter. It returns one Instant per session across the user's entire history. For somebody with 10k+ sessions over years, that's 10k objects instead of the old ~365 grouped rows per year.
- getMonthlyListeningPace loads alll audiobook sessions to memory. 🤦 
- still problems with separation of concern in regards to filtering/session (see for instance point above)

i am hoping these 2 are not that bad. By "not that bad", that this is still self-hosted app, not some big corpo site, so probably users do not have that "many" readingSession to cause actual problems, well at least i hope so. But this has already gotten too big. My apologies about that. If you have questions still i am open.

**Review by zachyale — APPROVED** [review]
