### PR TITLE
fix(ui): stabilize series browser virtual scroll

### LINKED ISSUE #865: Series View Broken
### Discussed in https://github.com/orgs/grimmory-tools/discussions/857

<div type='discussions-op-text'>

<sup>Originally posted by **aecreekmore** April 25, 2026</sup>
### What went wrong?

After updating to 3.0.0, the series view doesn't work. The book covers don't show up, and clicking on a series only works if you click 5+ times in quick succession. Hovering over a series makes the blank icons 'dance' back and forth. The view for a specific series once you manage to open it appears the same.

### How can we reproduce it?

1. Open series view
2. Attempt to open a series
3. Hover over series boxes

### What Build of Grimmory are you on?

Stable

### Your setup

- Grimmer 3.0.0
- Docker container running on MacOS
- I wiped my website data for Grimmory to make sure it was not a caching issue

### Screenshots or error messages (optional)

image

### Before submitting

- [X] I've searched existing discussions and this hasn't been reported yet
- [X] I've reviewed this report and have completed it as fully as I can</div>

### PR DESCRIPTION
**Pull request by alexhb1**
## Description

**Linked Issue:** Fixes #865 

Not the cleanest, its a workaround with the existing CDK browser and layout to stop the immediate regression. I have an idea for a clean refactor which should help all the browser pages but that's probably for another day :)

## Changes
- Fixed series browser freezing by stabilising CDK virtual scroll sizing and refresh behaviour

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed layout shifts caused by scrollbar appearance and disappearance in the series browser.

* **Performance Improvements**
  * Enhanced virtual scrolling rendering for smoother list performance and responsive viewport handling.

### CODE REVIEW

**Review by balazs-szucs — APPROVED** [review]
> I have an idea for a clean refactor which should help all the browser pages but that's probably for another day :)

Agreed :)

Approved, but make TODO note, so that you do not forget it :)

Thank you!

File: frontend/src/app/features/series-browser/components/series-browser/series-browser.component.ts [hunk 1]
```diff
@@ -195,6 +215,39 @@ export class SeriesBrowserComponent implements OnInit {
...
+      this.refreshViewport();
+    });
+  }
+
+  private refreshViewport(): void {
+    if (!this.virtualScroller) {
+      return;
+    }
+
+    const el = this.virtualScroller.elementRef.nativeElement as HTMLElement;
```
Comment (imnotjames) [inline frontend/src/app/features/series-browser/components/series-browser/series-browser.component.ts:246]: I'm guessing we have to cast here rather than satisfies or setting the const type, yeah?

**Review by imnotjames — APPROVED** [review]

File: frontend/src/app/features/series-browser/components/series-browser/series-browser.component.ts (hunk 1 above)
Comment (alexhb1) [reply frontend/src/app/features/series-browser/components/series-browser/series-browser.component.ts:246]: I just copied the pre-existing convention at line 78 but checking the CDK docs nativeElement already is HTMLElement, so it works either way.
